# Generated by Django 5.2.8 on 2026-06-19 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name_da', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('servings', models.DecimalField(decimal_places=2, default=4, max_digits=7)),
                ('guests', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('planned', 'Planned'), ('confirmed', 'Confirmed'), ('preparing', 'Being prepared'), ('prepared', 'Prepared'), ('eaten', 'Eaten'), ('skipped', 'Skipped'), ('replaced', 'Replaced'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('leftover_servings', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('recommendation_reasons', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planning.mealplan')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.mealtype')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMealParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portion_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('ate', models.BooleanField(blank=True, null=True)),
                ('planned_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='planning.plannedmeal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.householdmemberprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['household', 'start_date', 'end_date'], name='planning_me_househo_dead8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='valid_meal_plan_range'),
        ),
        migrations.AddConstraint(
            model_name='mealtype',
            constraint=models.UniqueConstraint(fields=('household', 'code'), name='unique_household_meal_type'),
        ),
        migrations.AddIndex(
            model_name='plannedmeal',
            index=models.Index(fields=['household', 'date', 'meal_type'], name='planning_pl_househo_bbf239_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedmeal',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'date', 'meal_type'), name='unique_meal_plan_slot'),
        ),
        migrations.AddConstraint(
            model_name='plannedmealparticipant',
            constraint=models.UniqueConstraint(fields=('planned_meal', 'profile'), name='unique_meal_participant'),
        ),
    ]
