# Generated by Django 5.2.8 on 2026-06-19 20:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('mock', 'Mock'), ('manual', 'Manual import'), ('api', 'Official API'), ('feed', 'Official feed')], max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=60)),
                ('attribution', models.TextField(blank=True)),
                ('terms_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('robots_reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroceryOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=250)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('package_size_text', models.CharField(blank=True, max_length=100)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('source_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_identifier', models.CharField(max_length=200)),
                ('product_identifier', models.CharField(blank=True, max_length=200)),
                ('original_source_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grocery_offers', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.store')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='offers.offerprovider')),
            ],
        ),
        migrations.CreateModel(
            name='OfferSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.offerprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=30)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.groceryoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIngredientMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('approved', models.BooleanField(default=False)),
                ('source', models.CharField(default='automatic', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='groceryoffer',
            index=models.Index(fields=['is_active', 'ends_at'], name='offers_groc_is_acti_86c337_idx'),
        ),
        migrations.AddIndex(
            model_name='groceryoffer',
            index=models.Index(fields=['store', 'is_active'], name='offers_groc_store_i_74444f_idx'),
        ),
        migrations.AddConstraint(
            model_name='groceryoffer',
            constraint=models.UniqueConstraint(fields=('provider', 'source_identifier', 'starts_at'), name='unique_provider_offer'),
        ),
        migrations.AddConstraint(
            model_name='productingredientmatch',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_product_ingredient_match'),
        ),
    ]
