# Generated by Django 5.2.8 on 2026-06-19 20:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('households', '0001_initial'),
        ('offers', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('package_size', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('packages', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('best_before_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('low', 'Low'), ('empty', 'Empty'), ('reserved', 'Reserved'), ('expiring', 'Expiring soon'), ('expired', 'Expired'), ('discarded', 'Discarded')], default='available', max_length=20)),
                ('grocery_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.groceryoffer')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('added', 'Added'), ('adjusted', 'Adjusted'), ('used', 'Used'), ('moved', 'Moved'), ('opened', 'Opened'), ('discarded', 'Discarded'), ('purchase', 'Purchase'), ('undo', 'Undo')], max_length=30)),
                ('quantity_delta', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryitem')),
                ('planned_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.plannedmeal')),
                ('reversed_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorytransaction')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('refrigerator', 'Refrigerator'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('cupboard', 'Cupboard'), ('basement', 'Basement'), ('garage', 'Garage'), ('custom', 'Custom')], default='pantry', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.storagelocation'),
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled'), ('too_much', 'Prepared too much'), ('disliked', 'Disliked'), ('storage', 'Storage problem'), ('damaged', 'Damaged packaging'), ('unknown', 'Unknown'), ('custom', 'Custom')], max_length=30)),
                ('custom_reason', models.CharField(blank=True, max_length=200)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ingredient')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_storage_name'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['household', 'status'], name='inventory_i_househo_f4d2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['household', 'expiration_date'], name='inventory_i_househo_818711_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['household', 'ingredient'], name='inventory_i_househo_255673_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_nonnegative'),
        ),
    ]
