# Generated by Django 5.2.8 on 2026-06-19 20:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('locale', models.CharField(default='da', max_length=10)),
                ('timezone', models.CharField(default='Europe/Copenhagen', max_length=50)),
                ('week_starts_on', models.PositiveSmallIntegerField(default=1)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseholdInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='households.household')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseholdMemberProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('age_group', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('senior', 'Senior'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20)),
                ('portion_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('daily_calorie_target', models.PositiveIntegerField(blank=True, null=True)),
                ('meal_targets', models.JSONField(blank=True, default=dict)),
                ('protein_target_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carbohydrate_target_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fat_target_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('dietary_preferences', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('foods_to_avoid', models.JSONField(blank=True, default=list)),
                ('disliked_foods', models.JSONField(blank=True, default=list)),
                ('favourite_foods', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='households.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('meal_type', models.CharField(max_length=50)),
                ('present', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='households.householdmemberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='householdmemberprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('household', 'user'), name='unique_household_linked_profile'),
        ),
        migrations.AddConstraint(
            model_name='attendanceschedule',
            constraint=models.UniqueConstraint(fields=('profile', 'weekday', 'meal_type'), name='unique_attendance_slot'),
        ),
        migrations.AddConstraint(
            model_name='attendanceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 1), ('weekday__lte', 7)), name='valid_weekday'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='households__user_id_2002ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('household', 'user'), name='unique_household_user'),
        ),
    ]
