# Generated by Django 5.2.8 on 2026-06-19 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_da', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('package_size', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('allergens', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('chain', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('provider_identifiers', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('supported_regions', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_da', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=12)),
                ('dimension', models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('count', 'Count'), ('other', 'Other')], max_length=20)),
                ('to_base_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=200)),
                ('normalized', models.CharField(db_index=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unit'),
        ),
        migrations.CreateModel(
            name='NutritionalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis_quantity', models.DecimalField(decimal_places=3, default=100, max_digits=12)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrate_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fibre_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('micronutrients', models.JSONField(blank=True, default=dict)),
                ('quality', models.CharField(choices=[('verified', 'Verified'), ('imported', 'Imported'), ('calculated', 'Calculated'), ('estimated', 'Estimated')], default='estimated', max_length=20)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_records', to='catalog.ingredient')),
                ('basis_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unit'),
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(default='da', max_length=10)),
                ('alias', models.CharField(max_length=150)),
                ('normalized', models.CharField(db_index=True, max_length=150)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('locale', 'normalized'), name='unique_ingredient_alias')],
            },
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name_da', 'name_en'), name='unique_ingredient_names'),
        ),
    ]
