# Generated by Django 5.2.8 on 2026-06-19 20:49

import django.core.validators
import django.db.models.deletion
import recipes.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('servings', models.DecimalField(decimal_places=2, default=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preparation_minutes', models.PositiveIntegerField(default=0)),
                ('cooking_minutes', models.PositiveIntegerField(default=0)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrate_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fibre_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nutrition_quality', models.CharField(default='missing', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('attribution', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('household', 'Household'), ('public', 'Public')], default='household', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=recipes.models.recipe_image_path)),
                ('alt_text', models.CharField(max_length=250)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.recipe')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('preparation', models.CharField(blank=True, max_length=200)),
                ('optional', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.recipe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecipeNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household_visible', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recipes.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['household', 'name'], name='recipes_rec_househo_0dd990_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['household', 'visibility'], name='recipes_rec_househo_88893b_idx'),
        ),
        migrations.AddConstraint(
            model_name='favouriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favourite_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipeinstruction',
            constraint=models.UniqueConstraint(fields=('recipe', 'position'), name='unique_recipe_step'),
        ),
    ]
