# Generated by Django 5.2.8 on 2026-06-19 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('households', '0001_initial'),
        ('offers', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('shopping', 'Shopping'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirmed_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('meal_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.mealplan')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.store')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(max_length=200)),
                ('required_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('available_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('purchase_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('preferred_brand', models.CharField(blank=True, max_length=150)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('unavailable', models.BooleanField(default=False)),
                ('estimated_regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.groceryoffer')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
                ('source_meals', models.ManyToManyField(blank=True, to='planning.plannedmeal')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.store')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shopping.shoppinglist')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.shoppinglistitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['household', 'status'], name='shopping_sh_househo_b7e1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'checked'], name='shopping_sh_shoppin_615096_idx'),
        ),
    ]
